### ISSUE TITLE
Not sure if it's on your end, crashing at SP world gen

### ISSUE THREAD

**Issue by SattesKrokodil** [Fusion-Flux/Supernatural-Crops#15]
**https://pastebin.com/GGp42TpS**

if it's not a problem with your (awesome) mod just delete the issue

**Comment by Leo40Git** [comment]
This should be fixed in 2.0.1, AFAIK? Try redownloading.

**Comment by ZenoMetal** [comment]
I have that issue too and I play on 2.0.2

**Comment by Fusion-Flux** [comment]
can you post some logs?

**Comment by SattesKrokodil** [comment]
This apperently got fixed with 2.0.2 for me

**Comment by Leo40Git** [comment]
@SattesKrokodil Please close this issue.
@ZenoMetal Please create a new issue with a crash report and logs.

**Comment by ZenoMetal** [comment]
I updated to 1.16.5 and that fixed it for me
