### ISSUE TITLE
add data driven crops (mystical creations, but for this)

### ISSUE THREAD

**Issue by Nathan22211** [Fusion-Flux/Supernatural-Crops#2]
would probably help you, and other modders, with adding crops

**Comment by hYdos** [comment]
concern

**Comment by hYdos** [comment]
im assigning myself so @Fusion-Flux wont fuck it up

**Comment by gdude2002** [comment]
poorly aged things

**Comment by Fusion-Flux** [comment]
Sorry for the late reply Nathan but currently adding data driven crops is not possible due to how berry bushes are currently coded but ill keep this open in case in the future mojang decides to un hardcode berry bush code.

**Comment by Fusion-Flux** [comment]
After some thinking I realized a much better solution. what I could do is create a datapack which allows crops to be data driven.

**Comment by Fusion-Flux** [comment]
I will start making this datapack as soon as possible.

**Comment by Fusion-Flux** [comment]
This is now in development as a base feature for SC Closing
